# Generated by Django 5.0.2 on 2024-03-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='status',
            field=models.CharField(default='2021-01-02', max_length=50),
            preserve_default=False,
        ),
    ]
