# Generated by Django 5.0.2 on 2024-03-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_classroom_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='class_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
