# Generated by Django 5.0.2 on 2024-04-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_useraccount_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='teacher',
            field=models.CharField(max_length=50),
        ),
    ]
