# Generated by Django 5.0.2 on 2024-04-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_classroom_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
