# Generated by Django 5.0.2 on 2024-04-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_classroom_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='batch',
            field=models.CharField(default=2024, max_length=50),
        ),
    ]
