# Generated by Django 5.0.2 on 2024-04-28 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_delete_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('a', models.CharField(max_length=250)),
                ('b', models.CharField(max_length=250)),
                ('c', models.CharField(max_length=250)),
                ('d', models.CharField(max_length=250)),
                ('answer', models.CharField(max_length=1)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assessment')),
            ],
        ),
        migrations.DeleteModel(
            name='MasteryLevel',
        ),
    ]
