# Generated by Django 5.0.2 on 2024-04-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_useraccount_mastery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(max_length=550),
        ),
    ]
