# Generated by Django 5.0.2 on 2024-04-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_assessment_type_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='with_image',
            field=models.BooleanField(default=0),
        ),
    ]
